# Generated by Django 5.1.6 on 2025-03-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='driver',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='user.color'),
        ),
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='model',
            field=models.CharField(max_length=50, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='driver',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Plate Number'),
        ),
        migrations.AddField(
            model_name='driver',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver/license/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
