# Generated by Django 5.1.6 on 2025-03-02 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_driver_vehicle_driver_color_driver_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_expiry_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
