# Generated by Django 5.1.6 on 2025-03-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/vehicle/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/licenses/'),
        ),
    ]
