# Generated by Django 5.1.6 on 2025-03-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_driver_image_alter_driver_license_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(default='uz', max_length=2),
        ),
    ]
