# Generated by Django 5.1.6 on 2025-03-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_full_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
