# Generated by Django 5.1.6 on 2025-03-03 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_country_parent'),
        ('group', '0003_alter_channel_options_channel_invite_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='common.country'),
        ),
    ]
