# Generated by Django 5.1.6 on 2025-03-07 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='who_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_groups', to=settings.AUTH_USER_MODEL, to_field='telegram_id'),
        ),
    ]
