# Generated by Django 5.1.6 on 2025-03-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_who_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='invite_link',
        ),
    ]
