# Generated by Django 5.1.6 on 2025-03-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_remove_group_description_remove_group_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('supergroup', 'SuperGroup'), ('channel', 'Channel')], default='group', max_length=255),
        ),
    ]
