# Generated by Django 5.1.6 on 2025-03-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_group_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('supergroup', 'SuperGroup'), ('channel', 'Channel')], db_index=True, default='group', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
