# Generated by Django 5.1.6 on 2025-03-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='order',
            name='from_where',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='to_where',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
