# Generated by Django 5.1.6 on 2025-03-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_options_order_from_where_order_to_where'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='when',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
