# Generated by Django 5.1.6 on 2025-03-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
